### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by xemxx** [happyapplehorse/gptui#31]
error msg in pip install .

```bash
❯ pip install .            
Processing /home/xem/Code/gpt/gptui
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting agere<1,>=0.1.1 (from gptui==0.4.4)
  Using cached agere-0.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting ai-care<1,>=0.1.2 (from gptui==0.4.4)
  Using cached ai_care-0.1.3-py3-none-any.whl.metadata (6.0 kB)
Collecting aiofiles<24,>=23.1.0 (from gptui==0.4.4)
  Using cached aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)
Collecting beautifulsoup4<5,>=4.12.2 (from gptui==0.4.4)
  Downloading beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 kB 1.8 MB/s eta 0:00:00
Collecting blinker<2,>=1.6.2 (from gptui==0.4.4)
  Using cached blinker-1.7.0-py3-none-any.whl.metadata (1.9 kB)
Collecting chardet<6,>=5.1.0 (from gptui==0.4.4)
  Downloading chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Collecting geocoder<2,>=1.38.1 (from gptui==0.4.4)
  Using cached geocoder-1.38.1-py2.py3-none-any.whl (98 kB)
Collecting httpx<1,>=0.24.1 (from gptui==0.4.4)
  Using cached httpx-0.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting lxml<5,>=4.9.3 (from gptui==0.4.4)
  Using cached lxml-4.9.4-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting openai<2,>=1.2.0 (from gptui==0.4.4)
  Using cached openai-1.6.1-py3-none-any.whl.metadata (17 kB)
Collecting playsound<2,>=1.3.0 (from gptui==0.4.4)
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "/home/xem/Code/gpt/gptui/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/xem/Code/gpt/gptui/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/xem/Code/gpt/gptui/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-t9vvn7n8/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-t9vvn7n8/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-t9vvn7n8/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-t9vvn7n8/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "/usr/lib/python3.11/inspect.py", line 1262, in getsource
          lines, lnum = getsourcelines(object)
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/inspect.py", line 1244, in getsourcelines
          lines, lnum = findsource(object)
                        ^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/inspect.py", line 1081, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

看起来像依赖更新了的问题？

无法正常安装依赖包

**Comment by happyapplehorse** [comment]
Please install the build tools first. 
```bash
pip install wheel setuptools
```
You can refer to [troubleshooting](/docs/troubleshooting.md).

**Comment by happyapplehorse** [comment]
I hope your issue has been resolved. If there are still problems, please reopen.

**Comment by xemxx** [comment]
> I hope your issue has been resolved. If there are still problems, please reopen.

I will be testing tonight, sorry work has been a little busy

**Comment by xemxx** [comment]
> I hope your issue has been resolved. If there are still problems, please reopen.

Thanks for the reply, this works!
